mail.enabled=true
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.username=marwenhamrouni52@gmail.com
mail.password=xlajouccgibwpzmj
mail.from=marwenhamrouni52@gmail.com
mail.notification.to=marwenhamrouni52@gmail.com
